defaults:
  - dataset: fast


experiment:
  name: mini_grp
  project: mini-grp
  description: "simple env with 64pix images and pose data"

# Model type: "transformer" or "convnet"
model: 
  type: "convnet"

batch_size: 128 # how many independent sequences will we process in parallel?
max_block_size: 12 ## Will be overidden by code
vocab_size: 32 ## Will be overidden by code
n_patches: 8
patch_size: 8
max_iters: 100000
eval_interval: 100 # How often to run eval over the validation set
learning_rate: 3e-3
eval_iters: 10
policy:
  action_stacking: 1
  obs_stacking: 1
  use_image_augmentations: false
  dtype: 'float32'
  use_pose_data: 1

testing: false
eval_vid_iters: 2500
gradient_accumulation_steps: 1

simEval: ["simple_env"] # "simpler_env" or "libero"
sim:
  eval_episodes: 5
  eval_tasks: [9, 24, 30, 69]
  episode length: 500

# ------------

r_seed: 1337
device: "cuda"
n_embd: 256
n_head: 16
n_blocks: 4
dropout: 0.2
action_dim: 7
load_action_bounds: true


## Model hyperparameters
image_shape: [64, 64, 3]
data_shuffel_interval: 1000 ## How often to reshuffle the data buffer, grabbing new random sequences from the cloud.

profiler:
  enable: false
  params:
    # record_shapes: true
    profile_memory: true
    with_stack: true
    use_cuda: true